name: build_vs

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build_vs2017_sln:
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v1
      - name: .Net Build
        uses: EasyDesk/action-dotnet-build@v1.0.0

